<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0-android;net9.0-windows10.0.19041.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseMaui>true</UseMaui>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileBridge.Domain\FileBridge.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Zeroconf" />
    <PackageReference Include="sqlite-net-pcl" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

</Project>
